### ISSUE TITLE
搜索栏的清除按钮点击没有触发onChange方法

### ISSUE THREAD

**Issue by dapengJia** [rsuite/rsuite-checktreepicker#2]
### One-line summary [问题简述]

搜索栏的清除按钮，点击之后应该触发onchange方法

### Version & Environment [版本及环境]
+ rsuite-checktreepicker version [rsuite-checktreepicker 版本]：
+ Browser version [浏览器类型和版本]：
+ OS Version [操作系统类型和版本]：
+ Other Environment Info [其他可以重现问题的环境信息]：

### Expected behaviour [期望结果]

搜索栏的清除按钮，点击之后应该触发onchange方法

**Comment by 15011120064** [comment]
文档没有完善，应该把onclean方法暴露出来
